method: grid
metric:
  goal: minimize
  name: loss
parameters:
  representation_name:
    value: 'molformer'
  batch_size:
    value: 4982
  num_epochs:
    values:
      - 1000
      - 10000
  latent_dim:
    value: 2
  lr:
    values:
      - 0.1
      - 0.01
      - 0.001
      - 0.05
  base_dir:
#    value: '../../../T5 EVO/alignment_olfaction_datasets/curated_datasets/'
    value: '/local_storage/datasets/farzaneh/'
  dataset_name:
    value: gslf
  seed:
    values:
      - 2024
      - 2025
      - 2026
      - 2027
      - 2028
  temperature:
    values:
     - 1
     - 0.9
     - 0.95
     - 0.8
     - 0.85
  normalize:
    value: True
  optimizer:
    value: 'poincare'
  model_name:
    value: 'contrastive'
  latent_dist_fun:
    value: 'poincare'
  distance_method:
    value: 'geo'
  distr:
    value: 'hypergaussian'
